version: 2
jobs:
  build:
    docker:
      - image: codehz/circleci-golang-upx:latest
    working_directory: /go/src/github.com/codehz/mcpeserver
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            go get gopkg.in/cheggaaa/pb.v1
            go get github.com/chzyer/readline
            go get github.com/valyala/fasttemplate
            go get github.com/google/subcommands
            go get github.com/kr/pty
            go get github.com/pwaller/goupx
            go get github.com/godbus/dbus
            go get github.com/coreos/go-systemd/daemon
            go get github.com/coreos/go-systemd/util
            go get github.com/coreos/go-systemd/journal
      - run: make

      - store_artifacts:
          path: /go/src/github.com/codehz/mcpeserver/mcpeserver

workflows:
  version: 2
  build:
    jobs:
      - build